name: Publish Mosaic 0.3.14 on DBR 11.3 LTS
on:
    workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./images/mosaic-0.3.14/dbr-11.3-lts/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:0.3.14-dbr-11.3-lts